config/routes.rb
EventManager::Application.routes.draw do
  resources :events do
    collection do
         get 'oldevents'
    end
    member do
         get 'close'
         put 'close_update'
         get 'attending'
         get 'maybeattending'
    end
  end
    
  get "pages/home"
  
  match 'login' => 'pages#login', :as => :login
  match 'logout' => 'pages#logout', :as => :logout
  
  match 'callback(/:code)' => 'pages#callback', :as => :callback
  match 'get_actual_statistics' => 'events#get_actual_statistics', :as => :get_actual_statistics
  
  root :to => 'pages#home'

end

app/models/event.rb
class Event < ActiveRecord::Base  
  attr_accessible :description, :end_time, :facebookID, :location, :name, :participants_declared, :participants_maybe, :participants_present, :picture, :privacy_type, :start_time, :status

  validates :name, :presence => true
  
  validates :start_time, :presence => true
  
  validates :status, :inclusion => { :in => [true, false] }
    
  validates :participants_declared, :numericality => true, :allow_blank => true
  validates :participants_maybe, :numericality => true, :allow_blank => true
  validates :participants_present, :numericality => true, :allow_blank => true
  
  #enum type simulation
  def self.privacy_type_list
    { 'Open'=> 'OPEN','Closed'=>'CLOSED', 'Secret' => 'SECRET' }
  end
  
  validate :date_present, :on => :create
  validate :valid_dates

  def valid_dates
    self.errors.add :end_time, ' cannot be before start time' if self.end_time && self.start_time >= self.end_time
  end
  def date_present
    self.errors.add :end_time, ' cannot be in the past' if self.end_time && self.end_time <= Time.now
  end
  

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :check_access_token, :except => [:index, :oldevents]
  before_filter :privacy, :except => [:index, :show, :oldevents, :destroy]
  before_filter :graph_api, :except => [:index, :oldevents]
   
  # GET /events
  # GET /events.json
  def index
    @events = Event.all(:conditions => ['status like ? ', true])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end
  
  def oldevents
    @events = Event.all(:conditions => ['status like ? ', false])
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  def attending
    @event = Event.find(params[:id])
    
    get_attending @event.facebookID
  end
  
  def maybeattending
    @event = Event.find(params[:id])
    
    get_attending @event.facebookID
  end
  
  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    
    params['facebook'] = {
      :name => params[:event][:name],
      :start_time => get_date_string_from_params(params[:event]['start_time(1i)'],params[:event]['start_time(2i)'],params[:event]['start_time(3i)'],params[:event]['start_time(4i)'],params[:event]['start_time(5i)']),
      :end_time => get_date_string_from_params(params[:event]['end_time(1i)'],params[:event]['end_time(2i)'],params[:event]['end_time(3i)'],params[:event]['end_time(4i)'],params[:event]['end_time(5i)']),
      :description => params[:event][:description],
      :location => params[:event][:location],
      :privacy_type => params[:event][:privacy_type]
      
      
    }
    
      @event = Event.new(params[:event])
      @event.status = true
      
      respond_to do |format|
        if @event.valid?
          faceresponse = @graph.put_object('me', 'events', params['facebook'] )
          if faceresponse
            @event.facebookID = faceresponse['id']
            @event.save
          
            format.html { redirect_to @event, notice: 'Event was successfully created.' }
            format.json { render json: @event, status: :created, location: @event }   
          else
            format.html { render action: "new", notice: 'Error on facebook occure.' }
          end
        else
          format.html { render action: "new" }
          format.json { render json: @event.errors, status: :unprocessable_entity }
        end
      end
    
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    
    params['facebook'] = {
      :name => params[:event][:name],
      :start_time => get_date_string_from_params(params[:event]['start_time(1i)'],params[:event]['start_time(2i)'],params[:event]['start_time(3i)'],params[:event]['start_time(4i)'],params[:event]['start_time(5i)']),
      :end_time => get_date_string_from_params(params[:event]['end_time(1i)'],params[:event]['end_time(2i)'],params[:event]['end_time(3i)'],params[:event]['end_time(4i)'],params[:event]['end_time(5i)']),
      :description => params[:event][:description],
      :location => params[:event][:location],
      :privacy_type => params[:event][:privacy_type]
      
      
    }
    	
    @event = Event.find(params[:id])
	@event.assign_attributes(params[:event])
	
    respond_to do |format|
      if @event.valid?
         faceresponse = @graph.put_object(@event.facebookID,'', params['facebook'] )
         if faceresponse == true
           @event.update_attributes(params[:event])
          
           format.html { redirect_to @event, notice: 'Event was successfully updated.' }
           format.json { head :no_content }
         else
           format.html { render action: "edit", notice: 'Error on facebook occure.' }
         end
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    faceresponse = @graph.delete_object(@event.facebookID)
    
    if faceresponse == true
      @event.destroy

      respond_to do |format|
        format.html { redirect_to events_url }
        format.json { head :no_content }
      end
    end
  end
  
  def close
    @event = Event.find(params[:id])
    
    can_close? @event
    
    get_attending @event.facebookID
  end
  
  def close_update
    #event = Event.new(params[:event])
	
	@event = Event.find(params[:id])
    @event.assign_attributes(params[:event])
	
    get_attending @event.facebookID
    
    @event.status = false
    
    respond_to do |format|
      if @event.valid?
        
           @event.update_attributes(params[:event])
        
        format.html { redirect_to events_url, :notice => "Closed successfully" }
      else
		#@event.update_attributes(params[:event])
        format.html { render action: "close" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def get_actual_statistics
    @events = Event.all(:conditions => ['status like ? ', true])
    
    @events.each do |event|
      get_attending event.facebookID
      event.update_attributes(:participants_declared => @attending.size, :participants_maybe => @maybe_attending.size)
      event.save
    end
      
    redirect_to events_path
  end
    
  protected
    def privacy
      @privacy_type = Event.privacy_type_list
    end
    
    def get_attending faceEventID
      @attending = @graph.get_connections(faceEventID, 'attending')
      @maybe_attending = @graph.get_connections(faceEventID, 'maybe')
    end
    
    def can_close? event
      redirect_to event_path, notice: 'Cannot close closed event.' if event.status == false
      redirect_to event_path, notice: 'Cannot close event that is not finished.' if (event.end_time && event.end_time > Time.now) || (event.end_time==nil && event.start_time + 10800 > Time.now )
    end
     
    def graph_api
      @graph ||= Koala::Facebook::API.new(session['access_token'])
    end

    def get_date_string_from_params(year,month,day,hour,minute)
      year + '-' + month + '-' + day + ' ' + hour + ':' + minute if (year.to_s+month.to_s+day.to_s+hour.to_s+minute.to_s).size!=0
    end
end

app/helpers/events_helper.rb
module EventsHelper
  
  def can_close_link? event     
    event.status == false || (event.end_time && event.end_time > Time.now) || (event.end_time==nil && event.start_time + 10800 > Time.now ) ? false : true
  end
  
  def can_edit? event
    event && event.status == false ? false : true
  end
end

app/views/events/_attendinglist.html.erb
<table>
  <tr>
    <th>Name</th>
    <th>Facebook user ID</th>
  </tr>

<% attend.each do |attending| %>
  <tr>
    <td><%= attending['name'] %></td>
    <td><%= attending['id'] %></td>
  </tr>
<% end %>
</table>

app/views/events/_eventslist.html.erb
<table>
  <tr>
    <th>Name</th>
    <th>Start time</th>
    <th>End time</th>
    <th>Location</th>
    <th>Participants declared</th>
    <th>Participants maybe</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @events.each do |event| %>
  <tr>
    <td><%= event.name %></td>
    <td><%= event.start_time %></td>
    <td><%= event.end_time %></td>
    <td><%= event.location %></td>
    <td><%= event.participants_declared %></td>
    <td><%= event.participants_maybe %></td>
    <td><%= link_to 'Show', event %></td>
    <td><%= link_to 'Edit', edit_event_path(event) %></td>
    <td><%= link_to 'Destroy', event, confirm: 'Are you sure?', method: :delete %></td>
    <% if can_close_link? event %>
    <td><%= link_to 'Close', close_event_path(event) %></td>
    <% end %>
  </tr>
<% end %>
</table>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    
    <% if can_edit? @event %>
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    <% else %>
      <%= f.label :name %><i>(Name of closed event cannot be changed)</i><br />
      <%= f.text_field :name,:disabled => true %>
    <% end %>
      
  </div>

  <div class="field">
    <% if can_edit? @event %>
      <%= f.label :start_time %><br />
      <%= f.datetime_select :start_time %>
    <% else %>
      <%= f.label :start_time %><i>(Start time of closed event cannot be changed)</i><br />
      <%= f.datetime_select :start_time,:disabled => true %>
    <% end %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br />
    <%= f.datetime_select :end_time, :include_blank => true %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :privacy_type %><br />
    <%= f.select :privacy_type,@privacy_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/attending.html.erb
<h1>Participants</h1>
<%= @attending.size %> already declared their presence

<%= render 'attendinglist', :attend => @attending %>

app/views/events/close.html.erb
<h1>Closing event</h1>

<%= form_for(@event, :url => close_update_event_path(@event)) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name,:disabled => true %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br />
    <%= f.datetime_select :start_time,:disabled => true %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br />
    <%= f.datetime_select :end_time, :include_blank => true,:disabled => true %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description,:disabled => true %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location,:disabled => true %>
  </div>
  <div class="field">
    <%= f.label :privacy_type %><br />
    <%= f.select :privacy_type,@privacy_type, {}, {:disabled => true} %>
  </div>
  <div class="field">
    <%= f.label :participants_declared %><i>(Value taken from facebook)</i><br />
    <%= f.number_field :participants_declared, :value => @attending.size  %>
  </div>
  <div class="field">
    <%= f.label :participants_maybe %><i>(Value taken from facebook)</i><br />
    <%= f.number_field :participants_maybe, :value => @maybe_attending.size  %>
  </div>
  <div class="field">
    <%= f.label :participants_present %><i>(Should be inserted manually)</i><br />
    <%= f.number_field :participants_present %>
  </div>
  <div class="actions">
    <%= f.submit 'Close event' %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing active events</h1>
<%= link_to 'Get actual statistics', get_actual_statistics_path %>

<%= render 'eventslist' %>

<br />

<%= link_to 'New Event', new_event_path %> | 
<%= link_to 'Old events', oldevents_events_path %>

app/views/events/maybeattending.html.erb
<h1>Participants</h1>
<%= @attending.size %> maybe would take part

<%= render 'attendinglist', :attend => @maybe_attending %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/oldevents.html.erb
<%= render 'eventslist' %>

<h1>Listing old events</h1>
<%= link_to 'Actual events', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Facebookid:</b>
  <%= @event.facebookID %>
</p>

<p>
  <b>Name:</b>
  <%= @event.name %>
</p>

<p>
  <b>Start time:</b>
  <%= @event.start_time %>
</p>

<p>
  <b>End time:</b>
  <%= @event.end_time %>
</p>

<p>
  <b>Description:</b>
  <%= @event.description %>
</p>

<p>
  <b>Location:</b>
  <%= @event.location %>
</p>

<p>
  <b>Privacy type:</b>
  <%= @event.privacy_type %>
</p>

<p>
  <b>Status:</b>
  <%= @event.status %>
</p>

<p>
  <b>Participants declared:</b>
  <%= @event.participants_declared %>
</p>

<p>
  <b>Participants maybe:</b>
  <%= @event.participants_maybe %>
</p>

<p>
  <b>Participants present:</b>
  <%= @event.participants_present %>
</p>


<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>


<h2>Participants Declared</h2>
<%= link_to 'Participants declared', attending_event_path(@event) %>
<h2>Participants Maybe</h2>
<%= link_to 'Participants maybe', maybeattending_event_path(@event) %>